systema/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login')
]

systema/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('logout/', views.signout, name='logout'),
    path('machines/', views.machine_list, name='machines'),
    path('add_machine/', views.add_machine, name='add_pc'),
    path('delete/<int:id>/', views.delete_pc, name='delete_pc'),
    path('edit/<int:id>/', views.edit_pc, name='edit_pc'),
    path('students/', views.student_list, name='students')
]

systema/systema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('core.urls')),
]

systema/core/models.py
from django.db import models

class Machine(models.Model):
    CONDITIONS = [
        ('Missing', 'MISSING'),
        ('Good', 'GOOD'),
        ('Broken', 'BROKEN')
    ]

    name = models.CharField(max_length=50, unique=True)
    condition = models.CharField(choices=CONDITIONS)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self): return self.name

class Student(models.Model):
    CLASSES = [
        ('form 1', 'FORM2'),
        ('form 2', 'FORM2'),
        ('form 3', 'FORM3'),
        ('form 4', 'FORM4'),
        ('Lower 6', 'L6'),
        ('Upper 6', 'U6'),
    ]

    name = models.CharField(max_length=50)
    student_class = models.CharField(choices=CLASSES)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self): return self.name

class Allocation(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self): return f'{self.machine} - {self.student}'

systema/accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Enter username'}))
    password = forms.CharField(widget=forms.PasswordInput({'class': 'input', 'placeholder': 'Enter password'}))

systema/core/forms.py
from django import forms
from .models import Machine

class MachineForm(forms.ModelForm):
    class Meta:
        model = Machine
        fields = ['name', 'condition']

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': "Enter name"}),
        }

systema/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm

def login_view(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                return redirect('home')
            else:
                return HttpResponse('Incorrect credentials!')

    else:
        form = LoginForm()

    return render(request, 'login.html', { 'form': form })

systema/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Machine, Allocation, Student
from .forms import MachineForm

@login_required(login_url='/auth/login')
def home(request):
    return render(request, 'core/home.html', { 'user': request.user, 'total_m_count': Machine.objects.count(), 'total_s_count': Student.objects.count(), 'good_pcs': Machine.objects.filter(condition="Good").count(), 'missing': Machine.objects.filter(condition="Missing").count() })

@login_required(login_url='/auth/login')
def signout(request):
    logout(request)
    return redirect('login')

@login_required(login_url='/auth/login')
def machine_list(request):
    if request.method == "GET":
        query = request.GET.get('q')
        machines = Machine.objects.filter(Q(name__icontains=query) | Q(condition__icontains=query)).order_by('-date_created') if query else Machine.objects.order_by('-date_created')
    else:
        machines = Machine.objects.order_by('-date_created')

    return render(request, 'core/machine_list.html', context={ 'machines': machines })

@login_required(login_url='/auth/login')
def add_machine(request):
    if request.method == 'POST':
        form = MachineForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('machines')
    
    else:
        form = MachineForm()

    return render(request, 'core/add_machine.html', context={ 'form': form })

@login_required(login_url='/auth/login')
def delete_pc(request, id):
   machine = get_object_or_404(Machine, pk=id)
   machine.delete()

   return redirect('machines')

@login_required(login_url='/auth/login')
def edit_pc(request, id):
    obj = get_object_or_404(Machine, pk=id)
    if request.method == 'POST':
        name = request.POST.get('name')
        condition = request.POST.get('condition')

        obj.name = name
        obj.condition = condition

        obj.save()
        return redirect('machines')

    

    return render(request, 'core/edit_pc.html', {  'obj': obj })

def student_list(request):
    # TODO: Add seacrch functionality for student's list
    return render(request, 'core/student_list.html', { 'students': Student.objects.order_by('-date_created') })

systema/accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Log In | Systema</title>
</head>
<body>
    <div class="container">
        <img src="{% static 'img/systema-logo.png' %}" alt="Systema Logo">
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form.username }}
            {{ form.password }}

            <button type="submit">Log In</button>
            <p>Programmed By Tafadzwa</p>
        </form>
    </div>
</body>
</html>

systema/core/templates/core/add_machine.html
{% extends 'core/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="box">
            <h1>Add a PC</h1>
            {{ form.name }}
            <p style="color: #fffefe;">Choose the condition of the PC</p>
            {{ form.condition }}
            <button class="btn btn-primary" type="submit">Add PC</button>
        </div>
    </form>
{% endblock %}

systema/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <title>Systema</title>
</head>
<body>
    {% include 'core/includes/navbar.html' %}

    <main class="content">
        {% block content %}{% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

systema/core/templates/core/edit_pc.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="box">
        <form method="post">
            {% csrf_token %}
            <h1>Edit PC</h1>
            <input name="name" value="{{ obj.name }}" type="text"required>
            <select name="condition" aria-op required id="id_condition">
                <option value="" selected>{{ obj.condition }}</option>
                <option value=""></option>
                    
                <option value="Missing">MISSING</option>

                <option value="Good">GOOD</option>

                <option value="Broken">BROKEN</option>

            </select>
            <button class="btn btn-primary" type="submit">Save</button>
        </form>
    </div>
{% endblock %}

systema/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Hi, {{ user }}!</h1>
    
    <div class="stats-card">
        <i class="fa-sharp fa-solid fa-laptop fa-beat-fade fa-3x"></i>
        <h1>All machines</h1>
        <p>Total no. {{ total_m_count }}</p>
    </div>

    <div class="stats-card">
        <i class="fa-solid fa-graduation-cap fa-spin-pulse fa-3x"></i>
        <h1>All students</h1>
        <p>Total no. {{ total_s_count }}</p>
    </div>

    <div class="stats-card">
        <i class="fa-solid fa-circle-check fa-spin fa-spin-reverse fa-3x"></i>
        <h1>Good PCs</h1>
        <p>Total no. {{ good_pcs }}</p>
    </div>

    <div class="stats-card">
        <i class="fa-solid fa-triangle-exclamation fa-spin-pulse fa-3x"></i>
        <h1>Missing PCs</h1>
        <p>Total no. {{ missing }}</p>
    </div>

{% endblock %}

systema/core/templates/core/includes/navbar.html
{% load static %}
<nav>
    <img src="{% static 'core/img/logo.png' %}" alt="">

    <span><a href="{% url 'home' %}">Home</a></span>
    <span><a href="{% url 'machines' %}">View PCs</a></span>
    <span><a href="{% url 'add_pc' %}">Add a PC</a></span>
    <span><a href="{% url 'students' %}">View Students</a></span>
    <span><a href="{% url 'logout' %}" class="logout">Log Out</a></span>
</nav>

systema/core/templates/core/machine_list.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Machine List</h1>

    <form method="get">
        <input name="q" class="search" type="text" placeholder="Search for a pc">
        <button type="submit" class="btn btn-primary">Search</button>

        <table class="table">
            <thead>
                <th>Name</th>
                <th>Condition</th>
                <th>Date Created</th>
            </thead>

            <tbody>
                {% for machine in machines %}
                    <tr>
                        <td>{{ machine.name }}</td>
                        <td>{{ machine.condition }}</td>
                        <td>{{ machine.date_created }}</td>
                        <td>
                            <a href="{% url 'delete_pc' machine.id %}" class="btn btn-danger">
                                <i class="fa-solid fa-trash"></i>
                            </a>

                            <a href="{% url 'edit_pc' machine.id %}" class="btn btn-primary">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

systema/core/templates/core/student_list.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Student List</h1>

    <table class="table">

        <thead>
            <th>Name</th>
            <th>Class</th>
            <th>Actions</th>
        </thead>

        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.name }}</td>
                    <td>{{ student.student_class }}</td>
                    <!-- TODO: Add other field and search box for students --->
                        <td>
                            <a href="" class="btn btn-danger">
                                <i class="fa-solid fa-trash"></i>
                            </a>

                            <a href="" class="btn btn-primary">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                        </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}